from sqlalchemy import Column, Integer, String, ForeignKey
from sqlalchemy.orm import declarative_base

Base1 = declarative_base()


class Liquidacao(Base1):
    __tablename__ = 'liquidacoes'
    id = Column(Integer, primary_key=True)
    codigo_municipio = Column(String)
    exercicio_orcamento = Column(String)
    codigo_orgao = Column(String)
    codigo_unidade = Column(String)
    data_emissao_empenho = Column(String)
    numero_empenho = Column(String)
    data_liquidacao = Column(String)
    data_referencia_liquidacao = Column(String)
    nome_responsavel_liquidacao = Column(String)
    numero_sub_empenho_liquidacao = Column(String)
    valor_liquidado = Column(String)
    estado_de_estorno = Column(String)
    estado_folha = Column(String)
    cpf_responsavel_liquidacao = Column(String)


class NotasPagamento(Base1):
    __tablename__ = 'notas_pag'
    id = Column(Integer, primary_key=True)
    codigo_municipio = Column(String)
    exercicio_orcamento = Column(String)
    codigo_orgao = Column(String)
    codigo_unidade = Column(String)
    data_emissao_empenho = Column(String)
    numero_empenho = Column(String)
    numero_sub_empenho = Column(String)
    numero_nota_pagamento = Column(String)
    data_referencia = Column(String)
    nu_documento_caixa = Column(String)
    data_nota_pagamento = Column(String)
    valor_nota_pagamento = Column(String)
    valor_empenhado_a_pagar = Column(String)
    estado_de_estornado = Column(String)
    cpf_pagador = Column(String)
    nome_pagador = Column(String)


class NotasFiscais(Base1):
    __tablename__ = 'notas_fiscais'
    id = Column(Integer, primary_key=True)
    codigo_municipio = Column(String)
    exercicio_orcamento = Column(String)
    codigo_orgao = Column(String)
    codigo_unidade = Column(String)
    data_emissao_empenho = Column(String)
    numero_empenho = Column(String)
    data_liquidacao = Column(String)
    tipo_nota_fiscal = Column(String)
    numero_nota_fiscal = Column(String)
    data_referencia = Column(String)
    numero_serie_selo_transito = Column(String)
    numero_selo_transito = Column(String)
    numero_serie = Column(String)
    numero_formulario = Column(String)
    data_limite = Column(String)
    cgf_emitente = Column(String)
    data_emissao = Column(String)
    valor_liquido = Column(String)
    valor_desconto = Column(String)
    valor_bruto = Column(String)
    valor_aliquota_iss = Column(String)
    valor_base_calculo_iss = Column(String)
    tipo_emissao = Column(String)
    numero_protocolo_autenticacao = Column(String)


class NotasEmpenho(Base1):
    __tablename__ = 'notas_empenho'
    id = Column(Integer, primary_key=True)
    codigo_municipio = Column(String)
    exercicio_orcamento = Column(String)
    codigo_orgao = Column(String)
    codigo_unidade = Column(String)
    data_emissao_empenho = Column(String)
    numero_empenho = Column(String)
    data_referencia_empenho = Column(String)
    codigo_funcao = Column(String)
    codigo_subfuncao = Column(String)
    codigo_programa = Column(String)
    codigo_projeto_atividade = Column(String)
    numero_projeto_atividade = Column(String)
    numero_subprojeto_atividade = Column(String)
    codigo_elemento_despesa = Column(String)
    modalidade_empenho = Column(String)
    descricao_empenho = Column(String)
    valor_anterior_saldo_dotacao = Column(String)
    valor_empenhado = Column(String)
    valor_atual_saldo_dotacao = Column(String)
    tipo_processo_licitatorio = Column(String)
    numero_documento_negociante = Column(String)
    estado_empenho = Column(String)
    numero_nota_anulacao = Column(String)
    data_emissao_empenho_substituto = Column(String)
    numero_empenho_substituto = Column(String)
    cd_cpf_gestor = Column(String)
    cpf_gestor_contrato = Column(String)
    data_contrato = Column(String)
    numero_contrato = Column(String)
    data_realizacao_licitacao = Column(String)
    numero_licitacao = Column(String)
    codigo_tipo_negociante = Column(String)
    nome_negociante = Column(String)
    endereco_negociante = Column(String)
    fone_negociante = Column(String)
    cep_negociante = Column(String)
    nome_municipio_negociante = Column(String)
    codigo_uf = Column(String)
    tipo_fonte = Column(String)
    codigo_fonte = Column(String)
